version: "3"
silent: true

vars:
  BINARY_NAME: zebra-serial-reader
  ENTRY_FILE: ./cmd/.
  BUILD_DIR: __dist
  BUILD_FILE: "./{{.BUILD_DIR}}/{{.BINARY_NAME}}.exe"
  RELEASE_FILE: "./{{.BUILD_DIR}}/{{.BINARY_NAME}}__upx.exe"
  LDFLAGS: -ldflags="-s -w"

tasks:
  run:
    desc: Run without build.
    cmd: go run {{.ENTRY_FILE}}

  build:
    desc: Build the binary file.
    cmd: go build -v {{.LDFLAGS}} -o {{.BUILD_FILE}} {{.ENTRY_FILE}}

  release:
    desc: Build the a release binary file.
    cmds:
      - go build -v {{.LDFLAGS}} -o {{.RELEASE_FILE}} {{.ENTRY_FILE}}
      - upx --best {{.RELEASE_FILE}}
    #ignore_error: true

  validate:
    # https://github.com/Boeing/config-file-validator
    desc: Validate config files.
    cmds:
      - echo '== Config file validator'
      - echo
      - validator --groupby pass-fail --exclude-dirs build,dist,node_modules,.svelte-kit
